name: CI

on:
  push:
    branches:
      - "master"
    paths:
      - "**.json"
  pull_request:
    branches:
      - "master"
    paths:
      - "**.json"

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Lint
        run: yarn run lint
